<a href="https://colab.research.google.com/github/changyui/changyui/blob/main/AI_ICT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#강의 1일차

In [ ]:
a=10
b=20
c=a+b
print(c)

30


In [ ]:
dir(time)

NameError: name 'time' is not defined

In [ ]:
import time
a = 10+10
for i in range(10):
    time.sleep(5)
    print(a)

In [ ]:
dir(keyword)

In [ ]:
import keyword
print(keyword.kwlist)

In [ ]:
from keyword import kwlist

In [ ]:
kwlist

In [ ]:
len(kwlist)

In [ ]:
xxx = 1234
print("xxx = ", xxx)
func_A = xxx
print("func_A = ", func_Aㅠ)
# 주석 처리

In [ ]:
a = False
b = True
a and b
# not b

In [ ]:
print("123", "\n\n", "456","\t\t", xxx, a)

In [ ]:
a = 'abc'
b = 1
type(b)
print('test')
print(type(a))
print('\n')
# print(a[1])
# len(a)

In [ ]:
a = 2
b = 1.5
c = a*b
print(type(a))
print(type(b))
print(type(c))

In [ ]:
str1 = "mom's burger. "
print(str1)

In [ ]:
str1 * 3

In [ ]:
d = "안녕하세요"
d[4]

In [ ]:
5//2

In [ ]:
5%2

In [ ]:
2**4

In [ ]:
d = "안녕하세요!!"
(d[0] + d[3] + d[5]) * 2

In [ ]:
pi = 3.131592
area = pi*3**2
area

In [ ]:
x = 10
x += 1
x

In [ ]:
i = 0
for i in range(1,11):
    i += 5
print(i)

In [ ]:
print("당신의 이름은 ? =")
x = input()
print("당신이 태어난 년도는 ? =")
y = input()
print(x, "님 반갑습니다. =")
y = 2022 - int(y) + 1
print("당신의 나의는", y, "세 입니다.")

In [ ]:
# a = '52.273'
# round(float(a))

In [ ]:
str_input = input("숫자 입력> ")
num_input = int(str_input)

print()
print(num_input, "inch")
print((num_input * 2.54), "cm")

숫자 입력> 1

1 inch
2.54 cm


In [ ]:
'파이썬 수업 {}만원'.format(5000)

'파이썬 수업 5000만원'

In [ ]:
'sEoul'.find('o')

2

In [ ]:
x = 'seoul'
print(x[x.find('o'):])

oul


In [ ]:
'school' in 'there is no school'

True

In [ ]:
a = "there is no school".split()
print(a)
print(a[2])

['there', 'is', 'no', 'school']
no


In [ ]:
y = 20
if y < 30:
    print("30보다 작습니다.")
else:
    print("30과 같거나 30보다 큽니다.")

30보다 작습니다.


In [ ]:
from datetime import datetime
print(datetime.now().year)
print(datetime.now().month)
print(datetime.now().day)
print(datetime.now().hour)

2022
6
12
15


In [ ]:
x = [10, 20, 30, 'abc', 'def',True, False,]
print(x[5:7])

[True, False]


In [ ]:
list_a = [[1,2,3],[4,5,6], [7,8,9]]
print(list_a[1])
print(list_a[1][2])

[4, 5, 6]
6


In [ ]:
dir(2)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [ ]:
x = range(10)
x = list(x)
print(x)
print([0,3,5,6,9])
print(x[0:10:2])
x[3] = 4
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 3, 5, 6, 9]
[0, 2, 4, 6, 8]
[0, 1, 2, 4, 4, 5, 6, 7, 8, 9]


In [ ]:
list_a = list(range(1,4))
list_b = list(range(4,7))
list_c = list_a + list_b
print(list_c)
# list_d = list_a * 3
# print(list_d)
list_e = [list_a, list_b]
print(list_e)
list_f = list_a.extend(list_b)
print(list_f)
print(list_a)
# list_a.insert(2,7)
# print(list_a)
# del list_a[2]
# print(list_a)

# list_a.remove(7)
# print(list_a)
# dir(list_a)

[1, 2, 3, 4, 5, 6]
[[1, 2, 3], [4, 5, 6]]
None
[1, 2, 3, 4, 5, 6]


In [ ]:
s = 0
j = 0
for i in 'a'*10:
    j += 1
    s += j
    print(j, s)

1 1
2 3
3 6
4 10
5 15
6 21
7 28
8 36
9 45
10 55


In [ ]:
import numpy as np
print(np.__version__)

1.21.5


In [ ]:
number = [273, 203, 5, 32, 65, 9, 72, 800, 99]
number_over_100 = []

count = 0
for number in number:
    if number >= 100:
        number_over_100.append(number)
        count += 1
        print("- 100 이상의 수 : ", number)
        print("* 그리고 새로이 생성된 리스트는 : ", number_over_100)
        print("\n")
print("100 이상의 수는 ", count, "개 있습니다.")

- 100 이상의 수 :  273
* 그리고 새로이 생성된 리스트는 :  [273]


- 100 이상의 수 :  203
* 그리고 새로이 생성된 리스트는 :  [273, 203]


- 100 이상의 수 :  800
* 그리고 새로이 생성된 리스트는 :  [273, 203, 800]


100 이상의 수는  3 개 있습니다.


In [ ]:
numbers = [273, 203, 5, 32, 65, 9, 72, 800, 99]
numbers_new = []

for numbers in numbers:
    if (numbers % 2) == 1:
        numbers_new.append(numbers)
        print("홀수인 수입니다.", numbers)
        print("새로이 생성된 리스트(업데이트)는 :.", numbers_new)
    

홀수인 수입니다. 273
새로이 생성된 리스트(업데이트)는 :. [273]
홀수인 수입니다. 203
새로이 생성된 리스트(업데이트)는 :. [273, 203]
홀수인 수입니다. 5
새로이 생성된 리스트(업데이트)는 :. [273, 203, 5]
홀수인 수입니다. 65
새로이 생성된 리스트(업데이트)는 :. [273, 203, 5, 65]
홀수인 수입니다. 9
새로이 생성된 리스트(업데이트)는 :. [273, 203, 5, 65, 9]
홀수인 수입니다. 99
새로이 생성된 리스트(업데이트)는 :. [273, 203, 5, 65, 9, 99]


In [ ]:
list_c = [[1,2,3],[4,5,6,7],[8,9]]
# i = 0
# j = 0

for i in list_c:
    print("i값은", i)
    for j in i:
        print("j값은", j)
        # print("값은 ", list_c)
        print('\n')

i값은 [1, 2, 3]
j값은 1


j값은 2


j값은 3


i값은 [4, 5, 6, 7]
j값은 4


j값은 5


j값은 6


j값은 7


i값은 [8, 9]
j값은 8


j값은 9




In [ ]:
score = float(input('학점을 입력 > '))
if score >= 4.5 :
    print('신')
elif score >= 4.2 :
    print('교수님의 사랑')
elif score >= 3.5 :
    print('현체제의 수호자')
elif score >= 2.8 :
    print('일반인')
elif score >= 2.3 :
    print('일탈을 꿈꾸는 소시민')
    
# 2.3까지만 하고 나머지는 마지막 0으로 조정

elif score >= 0 :
    print('시대를 앞서가는 혁명의 씨앗')

print('입력하신 학점은', score, '입니다.' )
print('종료')

학점을 입력 > 0
시대를 앞서가는 혁명의 씨앗
입력하신 학점은 0.0 입니다.
종료


In [ ]:
type(score)

float

# 강의 2일차

In [ ]:
score = [10,20,30]
print(score[0:])

[10, 20, 30]


In [ ]:
array = [273,32,103,"문자열",True,False]
print(array)
## 추가, 삭제, 특정값의 변경
## 서브셋
array.append(33)
print('추가후 1 :', array)

array.append({'나이':25})
print('추가후 2 :', array)

array.insert(0, 100)
print('변경후 1 :', array)

array1 = array[0:len(array)-1]
print('변경후 2 :', array1)

del array[-1]
print('변경후 3 :', array1)

aa = array.pop(0)
print('변경후 4 :', array)
print('pop()으로 추출한 값 :', aa)


array.append(100)
array.append(100)
array.append(100)
print('100 추가후 :', array)

for i in [1,1,1] :
  array.remove(100)
print('100 3번 삭제후 :', array)


# 아래는 리스트에 101 값이 없는데, 삭제하라고 해서 리스트에 없다고 오류메시지를 띄우는 것임
# array.remove(101)

print('현재 array1 :', array1)
for i in array1 :
  if 100 in array1 :
    array1.remove(100)
  
  else :
    pass
print('이후 array1 :', array1)

[273, 32, 103, '문자열', True, False]
추가후 1 : [273, 32, 103, '문자열', True, False, 33]
추가후 2 : [273, 32, 103, '문자열', True, False, 33, {'나이': 25}]
변경후 1 : [100, 273, 32, 103, '문자열', True, False, 33, {'나이': 25}]
변경후 2 : [100, 273, 32, 103, '문자열', True, False, 33]
변경후 3 : [100, 273, 32, 103, '문자열', True, False, 33]
변경후 4 : [273, 32, 103, '문자열', True, False, 33]
pop()으로 추출한 값 : 100
100 추가후 : [273, 32, 103, '문자열', True, False, 33, 100, 100, 100]
100 3번 삭제후 : [273, 32, 103, '문자열', True, False, 33]
현재 array1 : [100, 273, 32, 103, '문자열', True, False, 33]
이후 array1 : [273, 32, 103, '문자열', True, False, 33]


In [ ]:
array1 = [273,32,103,"문자열",True,False]
print('변경 전 : ', array1)
array2 = array1

for i in array2 :
  print('i 값은 : ', i)
  if i in array2 :
    array2.remove(i)
print('변경 후 : ', array2)

변경 전 :  [273, 32, 103, '문자열', True, False]
i 값은 :  273
i 값은 :  103
i 값은 :  True
변경 후 :  [32, '문자열', False]


In [ ]:
for i in range(1,10) :
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i,j  in enumerate(range(1,10)):
  print(i,j)


0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9


In [ ]:
name1 = ['a','b','c']
score1 = [90, 80, 70]

score = {'a':90, 'b':90, 'c':70}
for i in score :
  print(i)

a
b
c


In [ ]:
dict_a = {'name': '어벤져서엔드게임', 'type' : '히어로무비' }
print(dict_a)

dict_a['entrance'] = 1000
print(dict_a)

dict_a['entrance'] = 100000
print(dict_a)


{'name': '어벤져서엔드게임', 'type': '히어로무비'}
{'name': '어벤져서엔드게임', 'type': '히어로무비', 'entrance': 1000}
{'name': '어벤져서엔드게임', 'type': '히어로무비', 'entrance': 100000}


In [ ]:
dict_key = {
    'name' : 'df',
    'type' : 'dstf'
}


In [ ]:
dict_key = {
    0 : 'df',
    0 : 'dstf'
}

a = list(range(1,10))
# b = {0:a[0], 1:a[1]}

b = {}
j = 0
for i in a:
  b[j] = i
  j += 1

print(b)

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9}


In [ ]:
dictionary = {
    "name" : "7D 건조망고",
    "type" : "당절임",
    "ingredient" : ["망고", "설탕"],
    "origin" : "필리핀"
}

print(dictionary)

for i in dictionary :
  print(dictionary[i])

for i in dictionary :
  print(i)
print("===")

for i in dictionary.keys() :
  print(i)
print("===")

for i in dictionary.items() :
  print(i)
print("===")

{'name': '7D 건조망고', 'type': '당절임', 'ingredient': ['망고', '설탕'], 'origin': '필리핀'}
7D 건조망고
당절임
['망고', '설탕']
필리핀
name
type
ingredient
origin
===
name
type
ingredient
origin
===
('name', '7D 건조망고')
('type', '당절임')
('ingredient', ['망고', '설탕'])
('origin', '필리핀')
===


In [ ]:
numbers = [1,2,6,8,4,3,2,1,9,5,4,9,7,2,1,3,5,4,8,9,7,2,3]
counter = {}

for i in numbers :
 print(i)
  if counter.get(i) == None :
#    counter[i] = 1

# print(counter)

IndentationError: ignored

In [ ]:
character = {
    "name" : "기사",
    "level" : "12",
    "items" : {
        "sword" : "불꽃의 검",
        "armor" : "풀플레이트"
    },
    "skill" : ["베기","세게 베기", "아주 세게 베기"]
}
print(character)

# print(character.items())

for k in character :
  if type(character[k]) is not list :
    print(k,':', character[k])

  elif type(character[k]) is list :
    for j in character[k] :
      print("스킬:", j)


In [ ]:
character = {
    "name" : "기사",
    "level" : "12",
    "items" : {
        "sword" : "불꽃의 검",
        "armor" : "풀플레이트"
    },
    "skill" : ["베기", "세게 베기", "아주 세게 베기"]
}
# print(character)


for k in character :

  if type(character[k]) is not list :
    
    if type(character[k]) is dict :      
      for j in character[k] :
        print(j, ":", character[k][j])
    else :
      print(k,':', character[k])

  elif type(character[k]) is list :
    for j in character[k] :
      print(k, ":", j)

  #  for j in character[k] :
  #    print(k, ":", j)


In [ ]:
character = {
    "name" : "기사",
    "level" : "12",
    "items" : {
        "sword" : "불꽃의 검",
        "armor" : "풀플레이트"
    },
    "skill" : ["베기", "세게 베기", "아주 세게 베기"]
}
# print(character)


for k in character :

  if type(character[k]) is not list :
    
    if type(character[k]) is dict :      
      for j in character[k] :
        print(j, ":", character[k][j])
    else :
      print(k,':', character[k])

  elif type(character[k]) is list :
    for j in character[k] :
      print(k, ":", j)

  #  for j in character[k] :
  #    print(k, ":", j)


In [ ]:
start = 0
end = 100
step = 2

a = list(range(start,end,step))
print(a)
len(a)

for i in a :
  print("aaa "+ str(i))

In [ ]:
array = [232, 23, 103, 52, 57]
j = 0
for i in array:
  j += 1
  print(j, "번 성적은 :", i)

In [ ]:
sum = 0
for i in array :
  sum = sum+i
  print(sum)

In [ ]:
for i,v in enumerate(array) :
  print(i, "번째 반복", v)

In [ ]:
for i,v in enumerate(array) :
  print(f'{i} 번째 반복 : {v} 입니다.')

In [ ]:
for i in reversed(array) :
  print(i)

In [ ]:
a = [23,4,5,7,6]
x = 3
while x != 7 :
  print("aaaa")
  x = 7 

In [ ]:
a = [23,4,5,7,6]
x = None
i = 0
while x != 7 :
  x = a[i]
  i += 1
print(f'{i}번째에 7이 있습니다')

In [ ]:
a = [23,4,5,7,6]
i = 0
sum = 0
while i != len(a) :
  sum += a[i]
  i += 1
print(f'합은 {sum}입니다. 합계산은 {i}번 했습니다.')

In [ ]:
a = [23,4,5,7,6]

x = 0
s = 0
while True :
    if x == len(a) :
        break
    s += a[x]
    x += 1
    
print(f'합은 {s}입니다. 합계산은 {x}번 했습니다.')

In [ ]:
print(list(range(3,10,3)))
print(list(range(3,9,3)))

In [ ]:
key_list = ["name", "hp", "mp", "level"]
value_list = ["기사", 200, 30, 5]
character = {}

# i = 0
for i in range(len(key_list)) :
  character[key_list[i]] = value_list[i]


print(character)

In [ ]:
dict(zip(key_list, value_list))

In [ ]:
limit = 10000
i = 1
sum = 0

while sum <= limit :
  sum += i
  i += 1
print(f'합이 10000 보다 큰 경우의 합은 {sum}이며, 그때의 값은 {i}입니다.')

In [ ]:
n = 1
fac = 1

while n <= 10 :
  fac = fac*n
  n = n+1
print(f'팩토리일 값은 {fac}이며, 그때의 값은 {i}입니다.')

In [ ]:
n = 10
i = 1
value = 0

while i <= 10 :
  print("연산없음")
  i += 1
value = 100**n
print(value)

  

In [ ]:
n = 1
fac = 1

while n <= 10 :
  fac = fac*n
  n = n+1
print(f'팩토리얼 값은 {fac}이며, 그때의 값은 {i}입니다.')

j = 1
m = 10
value = 0

while j <= 10 :
#  print("연산없음")
  j += 1
value = 10**m
print("10의 m승 값은 ", value)

 

In [ ]:
n = 1
while True :
  exp = 10**n
  i = 1
  fac = 1
  while i <= n :
    fac = fac*i
    i += 1
  if fac > exp :
    print(f'팩토리얼은 {fac}이고, 10의 지수승은 {exp}이며, {n}부터 팩토리얼이 커집니다.')
    break
  n += 1 

In [ ]:
a = list(range(100))
print(f'{a[0]}부터 {a[99]}까지로 구성됨')

a_1 = []
for i in a :
  a_1.append(i**2)
print(a_1[99])

In [ ]:
a_2 = {key_list[i] : value_list[i] for i in range(4)}
print(a_2)

In [ ]:
a_3 = []
for i in a :
  if i%2 == 0 :
    a_3.append(i**2)
print(a_3)

In [ ]:
a_4 = [i**2 for i in a if i%2 == 0]
print(a_4)


In [ ]:
import random

x=[]
for i in range(100) :
  x.append(random.randint(1,100))
print(x)

In [ ]:
x_odds = []
for i in range(100) :
  if i % 3 == 0 :
    x_odds.append(i)
print(x_odds)

In [ ]:
x=[]
for i in range(100) :
  x.append(random.randint(1,100))
print(x)

x_1=[]
for i in range(1,101) :
  if i in x :
    pass
  else :
    x_1.append(i)

print(x_1)

In [ ]:
from collections import Counter
cnt = Counter(x)
# aa = [v for k,v in cnt.most_common()]

for i in cnt.most_common() :
  print(i)




In [ ]:
x_2 = [i for i in range(1,101) if i not in x ]
len(x_2)

In [ ]:
def f_name() :
  return "f_name 함수를 호출했습니다.."

f_name()


In [ ]:
x=[]
for i in range(100) :
  x.append(random.randint(1,101))
print(x)

def sum_odd(x) :
  s1 = 0
  for i in x :
     if i % 2 == 1 :
       s1 += i
  return s1

print(sum_odd(x))
print(sum_odd(x) / len(x))



In [ ]:
def print_n(value, n) :
  for i in range(n) :
    print(value)
  
print_n("반복", 10)

In [ ]:
y = x
y.append("이강욱")
sum(y)

In [ ]:
def sum_a(x) :
  x = [i for i in x if type(i) is not str]
  return sum(x)

sum_a(y)


In [ ]:
def str_print(x) :
  x = [i for i in x if type(i) is not str]
  if len(x) == 0 :
      print("발견된 문자열이 없습니다.")
      return x
  return x

str_print("이강욱")

In [ ]:
def exp_a(x=2, y=2) :
  return x**y

print(exp_a(10,10))


In [ ]:
def fac(n) :
  factorial = 1
  i = 1
  while i <= n :
     factorial = factorial*i
     i = i+1
  return factorial

print(fac(10))

In [ ]:
x = 2
while True :
  if fac(100) < exp_a(x,100) :
    print(x)
    break
  x += 1


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
def f(x) :
  return x**2 + 2*x + 1

print(f(2))

In [ ]:
def fac(n) :
  s = 1
  for i in range(1,n+1) :
      s = s*i
  return s

fac(3)



In [ ]:
def fac_1(n) :
  if n == 0 :
    return 1
  else :
      return n*fac(n-1)

fac_1(5)

In [ ]:
[1,2,3,]

In [ ]:
(1,2,3)[0]

In [ ]:
np.random.randn(3,4)


In [ ]:
np.ones(([3,4]))

In [ ]:
def f(x) :
  return x**2 + 2*x + 1

f1 = lambda x : x**2 + 2*x + 1

f1(10)

# y = map(lambda x : x**2 + 2*x + 1)


In [ ]:
x = [1,2,3,4,5]
y = [x**2 + 2*x + 1 for i in x]
print(y)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

x = load_iris()['data']
y = load_iris()['target']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =.2)

In [ ]:
%%time
a = map(lambda x:x**2,x)

In [ ]:
%%time
b = [i**2 for i in x]

In [ ]:
%%time
b = x**2

In [ ]:
from random import randint

In [ ]:
x = list(np.random.randint(1,100,10000))

In [ ]:
def mean(x) :
  return sum(x)/len(x)


강의자료(파이썬 기초)의 436페이지 할 차례

#강의 3일차

In [ ]:
import pandas as pd

In [ ]:
file = open("basic.txt", "w")
file.write("Hello ~")

In [ ]:
!pwd

In [ ]:
file.close()

In [ ]:
x = [1,2,3,4,5,6]
for i in x:
  try:
    print("test1")    
    print("dd{}",x**2)
  except:
    pass
    
print("test")

In [ ]:
import pandas as pd
import numpy as np
list_ab = np.random.randint(1,10,100)
list_ab

In [ ]:
import pandas as pd
import numpy as np

name = "윤인성 연하진 구지연 나선주 윤아린 윤명월".split()
korea = np.random.randint(60,100,6)
math = np.random.randint(60,100,6)
english = np.random.randint(60,100,6)
science = np.random.randint(60,100,6)
name

student = {'name': name[0], 'korea':korea[0], 'math':math[0]}
student = []
for i in range(6): 
  print("a")
  student = {'name': name[i], 'korea': korea[i], 'math': math[i],
             'english': english[i], 'science': science[i]}
  student
  #student = np.append(student, i, student[i])
  print("b")
student



In [ ]:
x = {'aa' : 12, 'bb' : 23}
# x.items()
print(x.keys())
print(x.values())

print(list(x.values()))

In [ ]:
x=3
result = x**2 + 2*x + 1
print(result)

In [ ]:
def f(x):
  return x**2 + 2*x + 1

print((3))

for i int x
  


In [ ]:
def ff(x):
  x = x+2
  print("a")
  return x**2 + 2*x + 1

ff(2)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits
# from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x = load_digits()['data']
y = load_digits()['target']

In [ ]:
def create_student(name, korea, math, english, science):
  student = {}
  student['name'] = name
  student['korea'] = korea
  student['math'] = math
  student['english'] = english
  student['science'] = science
  return student

create_student('이강욱',50, 60, 70, 80)

In [ ]:
class Student_class:
  pass

students = Student_class()

students = [
            
]

In [ ]:
def add(x,y):
  return x+y

def minus(x,y):
  return abs(x,y)

def divide(x,y):
  return x/y
  

In [ ]:
divide(3,4)

In [ ]:

class Cals :
  def __init__(self,x,y):
    self.x = x
    self.y = y

  def add(self):
    return self.x + self.y

  def minus(self):
    return self.x - self.y

  def divide(self):
    return self.x/self.y

  def anyone(self, k):
    return self.x + k

In [ ]:
cal = Cals(7,1)

In [ ]:
cal.add()

In [ ]:
cal.minus()

In [ ]:
cal.anyone(3)

In [ ]:
import math

class Student:
  aa=10
  def __init__(self,x1,x2,x3,x4,x5):
    self.name = x1
    self.korea = x2
    self.math = x3
    self.english = x4
    self.science = x5

  def total(self):
    self.total = self.korea + self.math + self.english + self.science
    self.len = 4
    return self.total

  def avr(self):
    return self.total/self.len



In [ ]:
student = Student('한글이름',1,2,3,4,)

In [ ]:
print(student.name)
print(student.korea)
student.total()
student.avr()

In [ ]:
student.aa

In [ ]:
math.pi

In [ ]:
student.science

In [ ]:
import numpy as np

In [ ]:
x_a = np.random.randint(1,100,10)
x_l = list(x_a)

print(x_a)
print(x_l)

# type(x_l)


앞의값은 데이터의 갯수, 뒤의 값은 

In [ ]:
type(x_a)
x_a + 3

In [ ]:
type(x_l)
x_l + 3

In [ ]:
np.shape(x_a)

In [ ]:
x_a.reshape(10,1)

In [ ]:
np.shape(x_a)

In [ ]:
x_a > 10

In [ ]:
x = np.array([3,5,2,6])
x[[True,False, False, True]]


In [ ]:
%%time
x = np.random.randint(1,30,100000000)

In [ ]:
%%time
cnt = 0
for i in x:
  if i % 10 ==0:
    cnt += 1

In [ ]:
x_l = list(np.random.randint(1,20,30))
x_a = np.array(x_l)
x_a.dtype
x_a


In [ ]:
x_a + 3

In [ ]:
x = x_a.astype(np.float)

In [ ]:
x.shape


In [ ]:
x = np.random.randint(1,10,30*40*50)
x_2 = x.reshape(-1,40*50)
x_3 = x.reshape(50,30,40)
x_4 = x_3.reshape(50,30,20,2)

In [ ]:
x_2.shape
x_3.shape

In [ ]:
x = np.array(['이강욱','이소은', 30, 11])
x[1].dtype

In [ ]:
korea = np.random.randint(60,100,10)
math = np.random.randint(60,100,10)
english = np.random.randint(60,100,10)

score = np.c_[korea, math, english]

score[:,0]

In [ ]:
score[:,1]

In [ ]:
score[:,2]

In [ ]:
np.sum(score, axis=0)

In [ ]:
np.sum(score, axis=1)

In [ ]:
x = np.array([1.3,3.,4])
x.dtype
# x =  x.astype(np.float32)
# x.dtype

In [ ]:
np.array([0,1,2,3],) + np.array([1])

In [ ]:
x = np.arange(4)
y = np.arange(4)
x = x.reshape(1,-1)
x = y.reshape(1,-1)


In [ ]:
x.shape

In [ ]:
x = np.arange(12)
x = x.reshape(3,4)
x

In [ ]:
y = np.arange(12)
y = y.reshape(3,4)
y*2

In [ ]:
x + y*2


In [ ]:
x  = np.arange(1,4)
x = x.reshape(3,1)
y = x.reshape(1,3)
(x+y).shape

In [ ]:
x

In [ ]:
y

In [ ]:
np.c_[x + y[0]]

In [ ]:
np.zeros([5,2])

In [ ]:
np.random.randn(5,2)

In [ ]:
x = np.random.randn(5,10)
x

In [ ]:
ones = np.zeros([5,10])
ones

In [ ]:
one1 = np.ones_like(ones)
one1

In [ ]:
a = np.empty([3,3])
a = np.eye(3, k=1)
a


In [ ]:
np.array([5]*10).shape

In [ ]:
np.identity(10)

In [ ]:
x = np.random.randn(10,10)
y = np.dot(x, np.identity(10))
y == x
#np.identity(10) 

In [ ]:
x = np.random.rand(10000)
np.mean(x)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x)

In [ ]:
np.random.seed(100)
array = np.arange(1,100)
x = np.random.choice(array,50)
np.sum(x)

In [ ]:
np.inf

In [ ]:
np.random.seed(100)
x = np.random.randint(1,50,1000)

In [ ]:
y_list = list(x)
y_list[[2,4,5]]

## 리스트에는 이렇게 접근할 수 가 없어서 에러가났고, 아래에 보면 넘파이어레이의 예시처럼 사용하면 맞게 실행됨

In [ ]:
x[[2,4,5]]

In [ ]:
y_list[2:6]

In [ ]:
np.sum(x[(x % 3 == 0) & (x % 5 == 0)])

In [ ]:
## x의 평균보다 큰수중 홀수만 가져와서 합 구하기

x_mean = np.mean(x)
np.sum(x[(x > x_mean)%2 == 1])


In [ ]:
np.square(x)

In [ ]:
np.random.seed(100)
x = np.random.randn(100)
np.random.seed(200)
y = np.random.randn(100)

In [ ]:
x

In [ ]:
z = (x - y)**2 / np.size(x)
sum(z)

In [ ]:
for i in range(len(x)):
  tmp = (x[i] - y[i])**2
  s_tmp += tmp
print(s-temp/tmp)


In [ ]:
np.std(x)

In [ ]:
np.percentile(x,3)

In [ ]:
np.median(x)

In [ ]:
x = np.random.randint(1,5,10)
x

In [ ]:
x = x.reshape(5,2)
x

In [ ]:
x = x.reshape(2,5)
x

In [ ]:
w = np.random.randn(2,10)
print(w)
print("\n")
w = w.reshape(5,-1)
print(w)

In [ ]:
x.shape

In [ ]:
w.shape

In [ ]:
np.dot(x,w).shape

In [ ]:
x = np.array([[[[1]]]])
x.ndim

In [ ]:
list2 = [1,3,chr(23123)]
np.array(list2).dtype

In [ ]:
array1 = np.arange(10000)
# sum(np.ravel(array2)) == array1/arrar1.size == True

In [ ]:
x = np.arange(5*3*7)
x.shape

(105,)

In [ ]:
y = x.reshape(3,5,-1)

In [ ]:
y.shape

(100,)

In [ ]:
from sklearn.datasets import load_iris
y = load_iris()['target']

In [ ]:
y = y.reshape(30, -1)
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
x = np.arange(100)
x[[True]*len(x)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
x[[True]*len(x)-2)+ [False]*3]

SyntaxError: ignored

In [ ]:
unorg_array = np.array([3,15,67,75,23])
org_array = np.sort(unorg_array)
org_array

array([ 3, 15, 23, 67, 75])

In [ ]:
x = np.random.randint(1,100,1000)
x = x.reshape(100, -1)
x = np.concatenate([x, np.sum(x, axis=1).reshape(100,-1)],axis=1)
x

array([[ 17,  60,  79, ...,  40,  62, 501],
       [ 67,  31,   2, ...,  84,  76, 584],
       [ 21,  55,  99, ...,  37,  63, 444],
       ...,
       [ 75,   9,  93, ...,   6,  92, 554],
       [ 58,  61,  46, ...,  91,  22, 448],
       [ 14,  57,  32, ...,  45,  89, 519]])

In [ ]:
x[np.argsort(x[:,-1]),:]

array([[ 14,  37,  37, ...,   7,  36, 263],
       [ 28,  40,  67, ...,  29,  16, 291],
       [  9,  34,   7, ...,  33,   5, 315],
       ...,
       [ 85,  90,  77, ...,  65,  30, 700],
       [ 76,  54,  14, ...,  78,  87, 721],
       [ 55,  83,  77, ...,  97,  96, 738]])

In [ ]:
x1 = np.random.randint(1,10,10)
x2 = np.random.randint(1,10,5)

In [ ]:
x1 = x1.reshape(-1,5)
x1


array([[2, 6, 3, 5, 9],
       [8, 6, 1, 2, 2]])

In [ ]:
x2

array([1, 8, 9, 7, 2])

In [ ]:
np.append(x1,x2)
# x2 = x2.reshape(-1,2)

array([2, 6, 3, 5, 9, 8, 6, 1, 2, 2, 1, 8, 9, 7, 2])

In [ ]:
x3 = np.concatenate([x1,x2])


ValueError: ignored

In [ ]:
x = np.random.randint(1,8,10000)
x.reshape(-1,1)

array([[3],
       [3],
       [2],
       ...,
       [2],
       [3],
       [7]])

In [ ]:
np.where(np.array([1,3,2]) >= 2, 1, 0)

array([0, 1, 1])

In [ ]:
y = x[:10]
y

array([3, 3, 2, 2, 3, 6, 6, 7, 6, 3])

In [ ]:
%%time
y_hat1 = np.where(x % 3 ==0,'3의배수',
            np.where(x % 5 == 0, '5의배수','나머지'))
y_hat1[0:10000]

# 위의 처리를 for문과 if-else문으로 처리하면 시간이 굉장히 오래걸림

CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 2.22 ms


# 강의 4일차

prun 유용함 

넘파이
1. 브로드 캐스팅
2. element wise 연산 (넘파이 사용 목적)

행렬형태의 shape이 있는 array = 텐서
* 일반적인 테서의 의미는 아님 

In [ ]:
# 램 용량 초과로 에러
# a = np.zeros((10000,1000000))

In [ ]:
import numpy as np
a = np.zeros(10, dtype=np.int16)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(a + 2)

[2 2 2 2 2 2 2 2 2 2]


In [ ]:
c = np.zeros(10, dtype=np.int16) + 1
print(c)

[1 1 1 1 1 1 1 1 1 1]


np.full((shape))

np.ones((shape))

np.zeros((shape))

np.arange()

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
a = np.full((3,4),np.pi)

## 4-1 : append()와 reshape()에 대한 예시

In [ ]:
import numpy as np
np.random.seed(0)  
x3 = np.random.randint(10, size=(3, 4, 5))  

x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [ ]:
x3[1]

array([[5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1]])

In [ ]:
(x3 + np.pi).dtype

dtype('float64')

In [ ]:
x3.shape

(3, 4, 5)

In [ ]:
x3[1,1,2]

3

In [ ]:
x3[0,2,:][1:4]
print("\n")
x3[1,2,:][1:4]

array([6, 8, 8])

array([3, 8, 1])

In [ ]:
x3[0:2,2,1:4]

array([[6, 8, 8],
       [3, 8, 1]])

In [ ]:
x3[0:2,[0,2],1:4][0,1]
x3[0:2,[0,2],1:4][1,0]

array([6, 8, 8])

array([9, 8, 9])

In [ ]:
np.append(x3[0:2,[0,2],1:4][0,1],x3[0:2,[0,2],1:4][1,0]).reshape(-1,3)

array([[6, 8, 8],
       [9, 8, 9]])

In [ ]:
a = x3[0:2,[0,2],1:4][0,1]
b = x3[0:2,[0,2],1:4][1,0]
c = np.concatenate([a, b]).reshape(-1,3)
c.ndim

2

In [ ]:
x3[0:2,[0,2],1:4]

array([[[0, 3, 3],
        [6, 8, 8]],

       [[9, 8, 9],
        [3, 8, 1]]])

In [ ]:
x3[0:2,[0,2],1:4].reshape(-1,3)

array([[0, 3, 3],
       [6, 8, 8],
       [9, 8, 9],
       [3, 8, 1]])

In [ ]:
x3[0:2,[0,2],1:4].reshape(-1,3)[1:3]

array([[6, 8, 8],
       [9, 8, 9]])

## 4-2 : swallow copy 와 deep copy

In [ ]:
 x3 = np.full((3,4,5),100)
 x3

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [ ]:
print(x3)
x4 = np.ones_like(x3)*100
x4

[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]


array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [ ]:
import numpy as np
np.random.seed(0)  
x3 = np.random.randint(10, size=(3, 4, 5))  

x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [ ]:
x4 = x3[1:,1:3,:]
x4

array([[[3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]]])

In [ ]:
x4 = np.ones_like(x4)+100
x4

array([[[101, 101, 101, 101, 101],
        [101, 101, 101, 101, 101]],

       [[101, 101, 101, 101, 101],
        [101, 101, 101, 101, 101]]])

In [ ]:
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [ ]:
a = np.array([2,2,5])
a

array([2, 2, 5])

In [ ]:
b = a.copy()
b

array([2, 2, 5])

In [ ]:
b[2] = 3
b

array([2, 2, 3])

In [ ]:
a

array([2, 2, 5])

newaxis

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x = np.array([1,2,3]).reshape(1,-1)
x

array([[1, 2, 3]])

In [ ]:

y = np.array([3,2,1]).reshape(1,-1)
np.concatenate([x,y],axis=0)


array([[1, 2, 3],
       [3, 2, 1]])

In [ ]:
np.concatenate([x,y],axis=1)

array([[1, 2, 3, 3, 2, 1]])

In [ ]:
np.random.seed(0)
x = np.random.randint(1,10,(4,3))

np.random.seed(1)
y = np.random.randint(1,10,(4,3))

In [ ]:
x

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9]])

In [ ]:
y

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [ ]:
np.c_[x,y]

array([[6, 1, 4, 6, 9, 6],
       [4, 8, 4, 1, 1, 2],
       [6, 3, 5, 8, 7, 3],
       [8, 7, 9, 5, 6, 3]])

In [ ]:
np.r_[x,y]

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9],
       [6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [ ]:
np.concatenate([x,y], axis=0)

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9],
       [6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [ ]:
np.concatenate([x,y], axis=1)

array([[6, 1, 4, 6, 9, 6],
       [4, 8, 4, 1, 1, 2],
       [6, 3, 5, 8, 7, 3],
       [8, 7, 9, 5, 6, 3]])

## 4-3 : numpy에 구현된 함수(적은시간)

In [ ]:
def xxx(x):
  for i in x:
    1.0/i
  return print("d")

In [ ]:
x = np.random.randint(1, 100, size=1000000)
%time 1.0/x
print("\n")
%time xxx(x)


CPU times: user 2.56 ms, sys: 4.29 ms, total: 6.85 ms
Wall time: 6.88 ms


array([0.02325581, 0.01612903, 0.02222222, ..., 0.01219512, 0.02439024,
       0.0212766 ])



d
CPU times: user 2.1 s, sys: 0 ns, total: 2.1 s
Wall time: 2.11 s


In [ ]:
x = np.arange(1,10000000)
%time sum(x)
print("\n")
%time np.sum(x)

CPU times: user 1.61 s, sys: 0 ns, total: 1.61 s
Wall time: 1.68 s


49999995000000



CPU times: user 14.1 ms, sys: 0 ns, total: 14.1 ms
Wall time: 17.1 ms


49999995000000

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)
x = np.random.randint(1, 20, size=1000000)

In [ ]:
%%time
acc = []
tmp = 0
for i in x:
  tmp += i
  acc.append(tmp)


CPU times: user 291 ms, sys: 33.7 ms, total: 324 ms
Wall time: 325 ms


In [ ]:
acc

In [ ]:
%time np.add.accumulate(x)

CPU times: user 4.01 ms, sys: 1.04 ms, total: 5.05 ms
Wall time: 8.47 ms


array([      13,       29,       30, ..., 10000193, 10000199, 10000200])

## 4-4 : 다양한 sort()

In [ ]:
np.random.seed(0)
x = np.random.randint(1, 1000, (5,10000000))

In [ ]:
x

array([[685, 560, 630, ..., 160, 727, 252],
       [101, 776, 198, ..., 295,  69,  86],
       [895, 216, 763, ..., 116, 693, 598],
       [501, 790, 308, ..., 395,  10, 134],
       [847, 159, 532, ..., 583,  67, 143]])

In [ ]:
# 1. 각 로우별 합계, 평균
y = np.random.rand(10,5)

s_a = []
for i in range(len(y)):
  s_a.append(np.sum(y[i,:]))

In [ ]:
s_a

[2.252796769415616,
 3.0146678454732463,
 1.637831065240108,
 2.2706393024138323,
 2.6361049741970484,
 3.7324622442594584,
 1.5552657922291586,
 2.8756890320371262,
 3.047424296068921,
 1.2462983909108267]

In [ ]:
y

array([[0.62505596, 0.87248094, 0.36767411, 0.35862506, 0.0289607 ],
       [0.54293892, 0.26297363, 0.7608283 , 0.94672278, 0.50120422],
       [0.00767058, 0.37408665, 0.29614398, 0.22699929, 0.73293056],
       [0.28612138, 0.96707156, 0.10182579, 0.25543018, 0.66019039],
       [0.25757167, 0.98011123, 0.11506607, 0.48280564, 0.80055037],
       [0.79881303, 0.43405489, 0.87453554, 0.71585204, 0.90920675],
       [0.29743556, 0.54853848, 0.39418009, 0.12334359, 0.19176806],
       [0.79996897, 0.69183689, 0.54504053, 0.82342952, 0.01541312],
       [0.85858731, 0.13038895, 0.4157953 , 0.82455229, 0.81810043],
       [0.11795685, 0.01412283, 0.36806102, 0.1824681 , 0.5636896 ]])

In [ ]:
np.min(y, axis=1)

array([0.0289607 , 0.26297363, 0.00767058, 0.10182579, 0.11506607,
       0.43405489, 0.12334359, 0.01541312, 0.13038895, 0.01412283])

In [ ]:
np.min(y, axis=0)

array([0.00767058, 0.01412283, 0.10182579, 0.12334359, 0.01541312])

In [ ]:
x = np.sort(y, axis=1) #[::-1]
x

array([[0.0289607 , 0.35862506, 0.36767411, 0.62505596, 0.87248094],
       [0.26297363, 0.50120422, 0.54293892, 0.7608283 , 0.94672278],
       [0.00767058, 0.22699929, 0.29614398, 0.37408665, 0.73293056],
       [0.10182579, 0.25543018, 0.28612138, 0.66019039, 0.96707156],
       [0.11506607, 0.25757167, 0.48280564, 0.80055037, 0.98011123],
       [0.43405489, 0.71585204, 0.79881303, 0.87453554, 0.90920675],
       [0.12334359, 0.19176806, 0.29743556, 0.39418009, 0.54853848],
       [0.01541312, 0.54504053, 0.69183689, 0.79996897, 0.82342952],
       [0.13038895, 0.4157953 , 0.81810043, 0.82455229, 0.85858731],
       [0.01412283, 0.11795685, 0.1824681 , 0.36806102, 0.5636896 ]])

In [ ]:
x[:,2]

array([0.87453554, 0.7608283 , 0.54504053, 0.4157953 , 0.39418009,
       0.36806102, 0.36767411, 0.29614398, 0.11506607, 0.10182579])

In [ ]:
def third_value(x):
  return x[np.argsort(x)[2]]

In [ ]:
for i in range(len(x))[0:10]:
  a = third_value(x[i,:])
  print(a)

0.015413123595598544
0.1179568450764964
0.25757166900690953
0.36767411475697176
0.36806102424857157
0.542938919359002
0.6918368918715343
0.8005503675140174
0.8181004334557647
0.9092067492707749


In [ ]:
np.apply_along_axis(third_value, 1, y)

array([0.36767411, 0.54293892, 0.29614398, 0.28612138, 0.48280564,
       0.79881303, 0.29743556, 0.69183689, 0.81810043, 0.1824681 ])

In [ ]:
np.apply_along_axis(lambda a: np.min(a), 0, y)

array([0.00767058, 0.01412283, 0.10182579, 0.12334359, 0.01541312])

## 4-5 : 판다스

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
ser = pd.Series(data=[100, 200, 300, 400, 500], index=['tom', 'bob', 'nancy', 'dan', 'eric'])
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
dtype: int64

In [ ]:
ser.index

Index(['tom', 'bob', 'nancy', 'dan', 'eric'], dtype='object')

In [ ]:
ser['nancy']

300

In [ ]:
ser2 = ser.to_dict()

In [ ]:
ser2

{'bob': 200, 'dan': 400, 'eric': 500, 'nancy': 300, 'tom': 100}

In [ ]:
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
dtype: int64

In [ ]:
ser_dict = {'index'+str(i) : v for i, v in enumerate(range(10))}
ser_dict

{'index0': 0,
 'index1': 1,
 'index2': 2,
 'index3': 3,
 'index4': 4,
 'index5': 5,
 'index6': 6,
 'index7': 7,
 'index8': 8,
 'index9': 9}

In [ ]:
ser['sin'] = 50
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
sin       50
dtype: int64

In [ ]:
ser * 2

tom       200
bob       400
nancy     600
dan       800
eric     1000
sin       100
dtype: int64

In [ ]:
ser = pd.Series(data=[100, 200, 300, 400, 500], 
                index=['tom', 'bob', 'nancy', 'dan', 'eric'])
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
dtype: int64

In [ ]:
ser.index[0]

'tom'

In [ ]:
ser[0]+10

110

In [ ]:
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
dtype: int64

In [ ]:
ser1 = ser + np.array([10,20,30,40,50])
ser1

tom      110
bob      220
nancy    330
dan      440
eric     550
dtype: int64

In [ ]:
d = {'col1' : pd.Series([100., 200., 300.], index=['apple', 'ball', 'clock']),
     'col2' : pd.Series([111., 222., 333., 4444.], index=['apple', 'ball', 'cerill', 'dancy'])}

In [ ]:
df = pd.DataFrame(d)
df

col1    col2
apple   100.0   111.0
ball    200.0   222.0
cerill    NaN   333.0
clock   300.0     NaN
dancy     NaN  4444.0

In [ ]:
df.index

Index(['apple', 'ball', 'cerill', 'clock', 'dancy'], dtype='object')

In [ ]:
df.columns

Index(['col1', 'col2'], dtype='object')

In [ ]:
df.values

array([[ 100.,  111.],
       [ 200.,  222.],
       [  nan,  333.],
       [ 300.,   nan],
       [  nan, 4444.]])

In [ ]:
df.head(3)

col1   col2
apple   100.0  111.0
ball    200.0  222.0
cerill    NaN  333.0

In [ ]:
df.tail(2)

col1    col2
clock  300.0     NaN
dancy    NaN  4444.0

In [ ]:
df['col1']

apple     100.0
ball      200.0
cerill      NaN
clock     300.0
dancy       NaN
Name: col1, dtype: float64

In [ ]:
df[['col1']]

col1
apple   100.0
ball    200.0
cerill    NaN
clock   300.0
dancy     NaN

In [ ]:
df['col3'] = df['col1'] + df['col2']
df

col1    col2   col3  col4
apple   100.0   111.0  211.0     3
ball    200.0   222.0  422.0     3
cerill    NaN   333.0    NaN     3
clock   300.0     NaN    NaN     3
dancy     NaN  4444.0    NaN     3

In [ ]:
df['col4'] = 3
df

col1    col2   col3  col4
apple   100.0   111.0  211.0     3
ball    200.0   222.0  422.0     3
cerill    NaN   333.0    NaN     3
clock   300.0     NaN    NaN     3
dancy     NaN  4444.0    NaN     3

In [ ]:
df['col5'] = np.random.randint(1,10, [5,1])
df

col1    col2   col3  col4  col5
apple   100.0   111.0  211.0     3     6
ball    200.0   222.0  422.0     3     2
cerill    NaN   333.0    NaN     3     7
clock   300.0     NaN    NaN     3     9
dancy     NaN  4444.0    NaN     3     7

In [ ]:
df['flag'] = df['col2'] > 250
df

col1    col2   col3  col4  col5   flag
apple   100.0   111.0  211.0     3     6  False
ball    200.0   222.0  422.0     3     2  False
cerill    NaN   333.0    NaN     3     7   True
clock   300.0     NaN    NaN     3     9  False
dancy     NaN  4444.0    NaN     3     7   True

In [ ]:
df.describe()

col1         col2        col3  col4      col5
count    3.0     4.000000    2.000000   5.0  5.000000
mean   200.0  1277.500000  316.500000   3.0  6.200000
std    100.0  2112.944628  149.199531   0.0  2.588436
min    100.0   111.000000  211.000000   3.0  2.000000
25%    150.0   194.250000  263.750000   3.0  6.000000
50%    200.0   277.500000  316.500000   3.0  7.000000
75%    250.0  1360.750000  369.250000   3.0  7.000000
max    300.0  4444.000000  422.000000   3.0  9.000000

In [ ]:
import matplotlib.pyplot as plt

df.describe().col2

count       4.000000
mean     1277.500000
std      2112.944628
min       111.000000
25%       194.250000
50%       277.500000
75%      1360.750000
max      4444.000000
Name: col2, dtype: float64

In [ ]:
df.col4.mean()

3.0

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/FederatedAI/FATE/master/examples/data/UCI_Credit_Card.csv')

In [ ]:
df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...        0.0        0.0        0.0       0.0     689.0   
1          0  ...     3272.0     3455.0     3261.0       0.0    1000.0   
2          0  ...    14331.0    14948.0    15549.0    1518.0    1500.0   
3          0  ...    28314.0    28959.0    29547.0    2000.0    2019.0   
4          0  ...    20940.0    19146.0    19131.0    2000.0   36681.0   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0   
29996     -1  ...     8979.0     5190.0        0.0    1837.0    3526.0   
29997     -1  ...    20878.0    20582.0    19357.0       0.0       0.0   
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0   
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0           0.0       0.0       0.0       0.0                           1  
1        1000.0    1000.0       0.0    2000.0                           1  
2        1000.0    1000.0    1000.0    5000.0                           0  
3        1200.0    1100.0    1069.0    1000.0                           0  
4       10000.0    9000.0     689.0     679.0                           0  
...         ...       ...       ...       ...                         ...  
29995    5003.0    3047.0    5000.0    1000.0                           0  
29996    8998.0     129.0       0.0       0.0                           0  
29997   22000.0    4200.0    2000.0    3100.0                           1  
29998    1178.0    1926.0   52964.0    1804.0                           1  
29999    1430.0    1000.0    1000.0    1000.0                           1  

[30000 rows x 25 columns]

In [ ]:
import pandas as pd
import numpy as np

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['area']


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.T

In [ ]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.iloc[0,2]

90.41392608386974

In [ ]:
data.describe()

area           pop     density
count       5.000000  5.000000e+00    5.000000
mean   316246.600000  2.337337e+07   93.639859
std    242437.411951  9.640386e+06   37.672251
min    141297.000000  1.288214e+07   38.018740
25%    149995.000000  1.955286e+07   85.883763
50%    170312.000000  1.965113e+07   90.413926
75%    423967.000000  2.644819e+07  114.806121
max    695662.000000  3.833252e+07  139.076746

In [ ]:
data.loc[(data.density > 100) & (data['pop'] < data['pop'].mean()), 'pop']

New York    19651127
Florida     19552860
Name: pop, dtype: int64

In [ ]:
dic = {
  'korea' : np.random.randint(60,101,100),
  'eng' : np.random.randint(60,101,100),
  'math' : np.random.randint(60,101,100),
  'sci' : np.random.randint(60,101,100)
}

In [ ]:
st = pd.DataFrame(dic)
st

korea  eng  math  sci
0      61   81    89   72
1      83   65    82   64
2      92   74    73   63
3      92   90    87   65
4      69   69    89   82
..    ...  ...   ...  ...
95     77   98    76   60
96     80   64    76   70
97     63   99    76   66
98     94   95    82   91
99     73   82    82   65

[100 rows x 4 columns]

In [ ]:
st['total'] = st.korea + st.eng + st.math + st.sci
st

korea  eng  math  sci  total
0      61   81    89   72    303
1      83   65    82   64    294
2      92   74    73   63    302
3      92   90    87   65    334
4      69   69    89   82    309
..    ...  ...   ...  ...    ...
95     77   98    76   60    311
96     80   64    76   70    290
97     63   99    76   66    304
98     94   95    82   91    362
99     73   82    82   65    302

[100 rows x 5 columns]

In [ ]:
st['mean'] = np.mean(st.loc[:, st.columns[:-1]], axis=1)
st

korea  eng  math  sci  total   mean
0      61   81    89   72    303  75.75
1      83   65    82   64    294  73.50
2      92   74    73   63    302  75.50
3      92   90    87   65    334  83.50
4      69   69    89   82    309  77.25
..    ...  ...   ...  ...    ...    ...
95     77   98    76   60    311  77.75
96     80   64    76   70    290  72.50
97     63   99    76   66    304  76.00
98     94   95    82   91    362  90.50
99     73   82    82   65    302  75.50

[100 rows x 6 columns]

In [ ]:
st['class'] = np.where(st['mean'] > 90, 'A', 
                       np.where(st['mean'] > 80, 'B', 'C'))
st

korea  eng  math  sci  total   mean class
0      61   81    89   72    303  75.75     C
1      83   65    82   64    294  73.50     C
2      92   74    73   63    302  75.50     C
3      92   90    87   65    334  83.50     B
4      69   69    89   82    309  77.25     C
..    ...  ...   ...  ...    ...    ...   ...
95     77   98    76   60    311  77.75     C
96     80   64    76   70    290  72.50     C
97     63   99    76   66    304  76.00     C
98     94   95    82   91    362  90.50     A
99     73   82    82   65    302  75.50     C

[100 rows x 7 columns]

In [ ]:
st.iloc[1]

korea      83
eng        65
math       82
sci        64
total     294
mean     73.5
class       C
Name: 1, dtype: object

In [ ]:
st.iloc[1][np.argmax(st.iloc[0,:4])]

82

In [ ]:
st.iloc[1][[np.argmax(st.iloc[0,:4])]]

math    82
Name: 1, dtype: object

In [ ]:
np.argmax(st.iloc[:,:4].values, axis=1)

array([2, 0, 0, 0, 2, 2, 1, 2, 3, 2, 1, 1, 0, 1, 3, 1, 2, 3, 2, 1, 0, 0,
       0, 3, 2, 2, 2, 3, 1, 1, 2, 3, 3, 2, 2, 3, 3, 1, 2, 2, 1, 3, 3, 1,
       2, 3, 0, 0, 1, 1, 0, 2, 3, 3, 3, 2, 3, 3, 2, 0, 0, 0, 2, 1, 2, 3,
       1, 1, 3, 2, 1, 3, 0, 1, 1, 3, 2, 2, 0, 2, 1, 0, 1, 1, 0, 3, 2, 3,
       2, 1, 1, 3, 1, 0, 1, 1, 0, 1, 1, 1])

In [ ]:
 st.columns[3]   
 
 # [np.argmax(st.iloc[:,:4].values, axis=1)]

'sci'

# 강의 5일차

## 5-1 : 복습

In [ ]:
import pandas as pd     # 엑셀데이터 형태(2차원 데이터) 다루기 쉽도록 만든 라이브러리 maded by 주식관련자
import numpy as np      # 브로트케스팅, 엘리멘트 연산

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
x1 = 5
x2 = np.array([1, 2, 3])
x3 = np.zeros([2,3])

In [ ]:
print(x3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
x2.shape

(3,)

In [ ]:
x3.shape

(2, 3)

In [ ]:
dir(x2)      # __iter__ 속성이 있는 반면, x1은 없음

In [ ]:
x4 = 5       # (에러예시) int 형은 이터레이션 속성이 없어서 for문 에러나옴

In [ ]:
for i in x4:
  print(i)

TypeError: ignored

In [ ]:
df = pd.DataFrame()

In [ ]:
  kor = np.random.randint(60,101,100)
  eng = np.random.randint(60,101,100)
  math = np.random.randint(60,101,100)
  sci = np.random.randint(60,101,100)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['kor'] = kor
df['eng'] = eng
df['math'] = math
df['sci'] = sci

In [ ]:
df

kor  eng  math  sci
0    79   79    81   91
1    72   83    65   89
2    65  100    91   80
3    94   94    78   95
4    76   90    76   82
..  ...  ...   ...  ...
95   98   97   100   79
96   62   62    96   89
97   74   93    68   92
98   68   96    87   71
99  100   77   100   96

[100 rows x 4 columns]

In [ ]:
df.to_csv("score.csv",index=None)

In [ ]:
data = pd.read_csv("score.csv")

In [ ]:
data.iloc[0,0:4]

kor     79
eng     79
math    81
sci     91
Name: 0, dtype: int64

In [ ]:
data['avg'] = np.mean(data.iloc[:,0:4], axis =1)

In [ ]:
data

kor  eng  math  sci   mean    avg
0    63   63    60   74  65.00  65.00
1    77   88    85   98  87.00  87.00
2    82   75    90   78  81.25  81.25
3    73   70    74   77  73.50  73.50
4    79   69    73   61  70.50  70.50
..  ...  ...   ...  ...    ...    ...
95   70   63    62   97  73.00  73.00
96   94   68    67   85  78.50  78.50
97   97   70    76   63  76.50  76.50
98   92   85    79   94  87.50  87.50
99   99   87    72   74  83.00  83.00

[100 rows x 6 columns]

In [ ]:
data.avg

0     82.50
1     77.25
2     84.00
3     90.25
4     81.00
      ...  
95    93.50
96    77.25
97    81.75
98    80.50
99    93.25
Name: avg, Length: 100, dtype: float64

In [ ]:
data["grade"]=np.where(data.avg > 90,'A',
         np.where(data.avg > 80,'B',
                 np.where(data.avg > 70,'C','D')))

In [ ]:
data

kor  eng  math  sci    avg grade
0    79   79    81   91  82.50     B
1    72   83    65   89  77.25     C
2    65  100    91   80  84.00     B
3    94   94    78   95  90.25     A
4    76   90    76   82  81.00     B
..  ...  ...   ...  ...    ...   ...
95   98   97   100   79  93.50     A
96   62   62    96   89  77.25     C
97   74   93    68   92  81.75     B
98   68   96    87   71  80.50     B
99  100   77   100   96  93.25     A

[100 rows x 6 columns]

In [ ]:
data.iloc[0,:4].values

array([79, 79, 81, 91], dtype=object)

In [ ]:
data.columns[np.argmax(data.iloc[0,:4].values)]

'sci'

In [ ]:
best_sub = []
for i in range(100):
    tmp = data.columns[np.argmax(data.iloc[:,:4].values,axis=1)[i]]
    best_sub.append(tmp)

In [ ]:
data['best_subject']=best_sub

In [ ]:
data

kor  eng  math  sci    avg grade best_subject
0    79   79    81   91  82.50     B          sci
1    72   83    65   89  77.25     C          sci
2    65  100    91   80  84.00     B          eng
3    94   94    78   95  90.25     A          sci
4    76   90    76   82  81.00     B          eng
..  ...  ...   ...  ...    ...   ...          ...
95   98   97   100   79  93.50     A         math
96   62   62    96   89  77.25     C         math
97   74   93    68   92  81.75     B          eng
98   68   96    87   71  80.50     B          eng
99  100   77   100   96  93.25     A          kor

[100 rows x 7 columns]

**loc & iloc 사용하기**

In [ ]:
import pandas as pd
import numpy as np
import math

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
popul = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'popul':popul})
data

area     popul
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['density'] = data['popul'] / data['area']
data

area     popul     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.loc[['California','New York'],['popul','density']]

popul     density
California  38332521   90.413926
New York    19651127  139.076746

In [ ]:
x = np.array(['California','Texas','New York','Florida','Illinois'])
x

array(['California', 'Texas', 'New York', 'Florida', 'Illinois'],
      dtype='<U10')

In [ ]:
data.loc[data.index.isin(['California','New York']),['popul','density']]

popul     density
California  38332521   90.413926
New York    19651127  139.076746

In [ ]:
data.loc[data.index.isin(['California','New York']), data.columns.isin(['popul','density'])]

popul     density
California  38332521   90.413926
New York    19651127  139.076746

In [ ]:
data.iloc[:,:]

area     popul     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
data.area.max()
# data.iloc[[],:]

695662

In [ ]:
data.loc[data.area.max() == data.area, ['popul','density']]

popul   density
Texas  26448193  38.01874

In [ ]:
data.iloc[0,:2]

area       423967.0
popul    38332521.0
Name: California, dtype: float64

In [ ]:
data.iloc[(data.density.values > 50),:2]

area     popul
California  423967  38332521
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data.density.values

array([ 90.41392608,  38.01874042, 139.07674614, 114.80612053,
        85.88376279])

In [ ]:
df1 = pd.DataFrame({
    'value' : [1, np.nan, 2, None]
})

In [ ]:
df1

value
0    1.0
1    NaN
2    2.0
3    NaN

In [ ]:
df2 = pd.DataFrame({
    'year' : [10, -10, np.nan,2, 'too many']
})

In [ ]:
df2

year
0        10
1       -10
2       NaN
3         2
4  too many

In [ ]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [ ]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [ ]:
df.fillna(0)

0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6

In [ ]:
dttm = []
dttm = np.arange(24)
#.astype('str')
dttm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a1 = str(dttm[1])
type(a1)

str

In [ ]:
dttm_str = []
dttm_str = np.arange(24).astype('str')

type(dttm_str[0])

numpy.str_

In [ ]:
for i in range(24):
  if dttm[i] < 10 :
    dttm_str[i] = dttm[i].astype('str') 
    dttm_str[i] ='0' + str(dttm_str[i])
    print(dttm_str[i])
    # print(type(dttm_str[i]))
  else :
    pass
    #dttm_str[i] = str(dttm[i])

print(type(dttm_str[10]))

00
01
02
03
04
05
06
07
08
09
<class 'numpy.str_'>


In [ ]:
dttm[1]

'1'

In [ ]:
dttm_str1 = np.random.choice(dttm_str, 1000)
dttm_str1

array(['12', '03', '14', '15', '06', '12', '18', '12', '05', '16', '05',
       '03', '11', '04', '16', '16', '05', '22', '13', '07', '02', '03',
       '06', '09', '10', '06', '09', '23', '04', '21', '02', '16', '09',
       '05', '08', '16', '08', '20', '20', '22', '21', '13', '01', '22',
       '19', '03', '06', '21', '00', '05', '10', '10', '15', '21', '13',
       '00', '08', '11', '22', '02', '20', '02', '09', '01', '03', '15',
       '20', '01', '12', '00', '03', '01', '06', '21', '01', '01', '23',
       '07', '14', '11', '14', '13', '23', '01', '21', '06', '20', '23',
       '21', '10', '11', '17', '23', '13', '02', '07', '02', '15', '07',
       '09', '01', '11', '18', '21', '16', '23', '17', '08', '09', '03',
       '14', '22', '14', '23', '17', '19', '03', '16', '09', '06', '14',
       '18', '16', '08', '02', '12', '16', '07', '18', '14', '00', '00',
       '16', '20', '13', '09', '08', '15', '07', '01', '22', '13', '15',
       '15', '13', '08', '12', '14', '11', '00', '1

In [ ]:
cnt = np.random.randint(0,5,1000)
cnt

array([1, 2, 2, 4, 4, 1, 3, 1, 2, 2, 1, 3, 3, 4, 2, 4, 0, 4, 1, 1, 2, 4,
       2, 1, 0, 3, 4, 1, 1, 3, 1, 2, 4, 3, 2, 2, 2, 2, 4, 2, 0, 3, 4, 0,
       1, 2, 3, 0, 1, 1, 3, 3, 0, 3, 0, 3, 1, 2, 4, 0, 4, 4, 4, 3, 4, 2,
       2, 0, 1, 0, 0, 2, 0, 2, 0, 1, 1, 0, 0, 2, 2, 0, 2, 4, 4, 4, 1, 1,
       4, 2, 0, 3, 2, 4, 0, 1, 0, 4, 0, 3, 1, 1, 3, 0, 4, 3, 0, 2, 2, 2,
       4, 2, 3, 4, 0, 1, 0, 3, 3, 3, 1, 0, 2, 3, 2, 2, 3, 1, 1, 4, 4, 3,
       1, 2, 4, 0, 3, 4, 2, 2, 2, 1, 2, 2, 4, 4, 1, 3, 1, 4, 2, 1, 1, 3,
       1, 4, 4, 3, 1, 2, 4, 3, 3, 3, 2, 3, 3, 4, 2, 2, 1, 0, 1, 1, 4, 0,
       1, 4, 3, 0, 1, 0, 4, 0, 4, 0, 2, 1, 2, 3, 3, 3, 4, 1, 0, 2, 1, 4,
       3, 4, 0, 4, 1, 0, 1, 3, 4, 3, 3, 3, 1, 4, 1, 0, 4, 1, 1, 0, 4, 3,
       3, 0, 4, 3, 4, 2, 2, 3, 0, 0, 3, 1, 3, 0, 4, 0, 4, 0, 2, 0, 2, 3,
       3, 3, 3, 0, 4, 1, 3, 2, 1, 4, 4, 1, 2, 3, 3, 2, 1, 3, 2, 4, 2, 3,
       0, 1, 3, 4, 3, 1, 0, 4, 2, 3, 4, 3, 3, 3, 4, 4, 1, 4, 0, 4, 0, 0,
       2, 2, 3, 0, 4, 0, 2, 2, 3, 4, 0, 2, 2, 0, 1,

In [ ]:
dt = pd.DataFrame()
dt['dttm'] = dttm_str1
dt['cnt'] = cnt
dt

dttm  cnt
0     12    1
1     03    2
2     14    2
3     15    4
4     06    4
..   ...  ...
995   14    1
996   13    1
997   13    3
998   09    0
999   13    0

[1000 rows x 2 columns]

In [ ]:
local = np.random.choice(['A','B','C'], 1000)

In [ ]:
dt['local'] = local
dt

dttm  cnt local
0     12    1     C
1     03    2     B
2     14    2     A
3     15    4     A
4     06    4     B
..   ...  ...   ...
995   14    1     C
996   13    1     A
997   13    3     B
998   09    0     A
999   13    0     C

[1000 rows x 3 columns]

In [ ]:
dt.pivot_table(index='local', 
               columns='dttm',
               aggfunc={'cnt':'sum'})

cnt                                      ...                          \
dttm   00  01  02  03  04  05  06  07  08  09  ...  14  15  16  17  18  19   
local                                          ...                           
A      29  36  28  18  31  18  29  17  36  24  ...  20  36  33  21  56  12   
B      24  44  14  37  20  32  23  12  46  36  ...  25  26  43  27  18  19   
C      48  28  32  10  35  28  23  27  29  35  ...  26  23  16  10  18  26   

                       
dttm   20  21  22  23  
local                  
A      28  30  28  29  
B      29  37  46   9  
C      43  32  38  26  

[3 rows x 24 columns]

In [ ]:
??pd.pivot

**Groupby 명령어 사용**

In [ ]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two', 'two'],
                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                    'baz': [1, 2, 3, 4, 5, 6],
                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

In [ ]:
df

foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [ ]:
df.pivot(index='foo', columns='bar', values='baz')

bar  A  B  C
foo         
one  1  2  3
two  4  5  6

In [ ]:
import seaborn as sns

In [ ]:
titanic = sns.load_dataset('titanic')

In [ ]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
np.sum(np.sum(titanic.isna()))

869

In [ ]:
titanic.groupby(['sex','pclass']).sum().reset_index()

sex  pclass  survived      age  sibsp  parch       fare  adult_male  \
0  female       1        91  2942.00     52     43  9975.8250           0   
1  female       2        70  2125.50     37     46  1669.7292           0   
2  female       3        72  2218.50    129    115  2321.1086           0   
3    male       1        45  4169.42     38     34  8201.5875         119   
4    male       2        17  3043.33     37     24  2132.1125          99   
5    male       3        47  6706.42    173     78  4393.5865         319   

   alone  
0     34  
1     32  
2     60  
3     75  
4     72  
5    264

In [ ]:
titanic.groupby('sex').aggregate(['mean','sum','count'])['survived']

mean  sum  count
sex                         
female  0.742038  233    314
male    0.188908  109    577

**pd.cut 사용하기**

In [ ]:
anything = pd.cut(titanic.age,[0, 18,35, 80])
titanic.groupby(anything).mean().fare

age
(0, 18]     32.500721
(18, 35]    29.925929
(35, 80]    43.966821
Name: fare, dtype: float64

In [ ]:
titanic.pivot_table('adult_male', index='sex',columns='class')

class     First    Second     Third
sex                                
female  0.00000  0.000000  0.000000
male    0.97541  0.916667  0.919308

In [ ]:
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [ ]:
??pd.melt

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [ ]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
age = pd.cut(titanic['age'], [0, 18, 80])
age.head(10)

0    (18.0, 80.0]
1    (18.0, 80.0]
2    (18.0, 80.0]
3    (18.0, 80.0]
4    (18.0, 80.0]
5             NaN
6    (18.0, 80.0]
7     (0.0, 18.0]
8    (18.0, 80.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 80]]

In [ ]:
titanic.groupby(age).mean().fare

age
(0, 18]     32.500721
(18, 80]    35.224840
Name: fare, dtype: float64

In [ ]:
titanic.pivot_table('adult_male',index='sex', columns='class')

class     First    Second     Third
sex                                
female  0.00000  0.000000  0.000000
male    0.97541  0.916667  0.919308

In [ ]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                   'Eric Idle', 'Terry Jones', 'Michael Palin'])
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [ ]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [ ]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [ ]:
monte = pd.DataFrame(monte)
monte['salary'] = np.random.randint(100,200,6)
monte.columns = ['name', 'salary']

In [ ]:
monte.loc[monte.name == 'Graham Chapman']

name  salary
0  Graham Chapman     102

In [ ]:
monte.name.str.capitalize()

0    Graham chapman
1       John cleese
2     Terry gilliam
3         Eric idle
4       Terry jones
5     Michael palin
Name: name, dtype: object

In [ ]:
monte.name.str.find(' ')

0    6
1    4
2    5
3    4
4    5
5    7
Name: name, dtype: int64

In [ ]:
monte.name.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
Name: name, dtype: object

In [ ]:
monte.name.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
Name: name, dtype: object

In [ ]:
j = 0
for i in monte.name.str.find(' '):
    print(monte.name[j][i+1:])
    j += 1

Chapman
Cleese
Gilliam
Idle
Jones
Palin


In [ ]:
monte.name.str.contains('Chapman')

0     True
1    False
2    False
3    False
4    False
5    False
Name: name, dtype: bool

In [ ]:
from datetime import datetime

In [ ]:
now = datetime.now()
now

datetime.datetime(2022, 7, 10, 5, 34, 0, 905703)

In [ ]:
now.day

10

In [ ]:
date = pd.to_datetime('2022-07-10')
date

Timestamp('2022-07-10 00:00:00')

In [ ]:
import pandas as pd
date = pd.to_datetime("1 may, 2021")
date

Timestamp('2021-05-01 00:00:00')

In [ ]:
date + pd.to_timedelta(np.arange(12), 'h')

DatetimeIndex(['2021-05-01 00:00:00', '2021-05-01 01:00:00',
               '2021-05-01 02:00:00', '2021-05-01 03:00:00',
               '2021-05-01 04:00:00', '2021-05-01 05:00:00',
               '2021-05-01 06:00:00', '2021-05-01 07:00:00',
               '2021-05-01 08:00:00', '2021-05-01 09:00:00',
               '2021-05-01 10:00:00', '2021-05-01 11:00:00'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
??pd.to_timedelta

## 5-2 : 데이터 합치기

In [ ]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [ ]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [ ]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [ ]:
pd.merge(df3, df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

## 5-3 : 그룹핑

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [ ]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [ ]:
planets.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [ ]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [ ]:
planets.method.value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

**GroupBy : Split, Apply, Combine**

In [ ]:
grouped = planets.groupby('method')
grouped

for name, group in grouped:
    print('---------------------------s----------------------------')
    print(name)
    print(group.head())
    print('---------------------------e-----------------------------')

---------------------------s----------------------------
Astrometry
         method  number  orbital_period  mass  distance  year
113  Astrometry       1          246.36   NaN     20.77  2013
537  Astrometry       1         1016.00   NaN     14.98  2010
---------------------------e-----------------------------
---------------------------s----------------------------
Eclipse Timing Variations
                       method  number  orbital_period  mass  distance  year
32  Eclipse Timing Variations       1        10220.00  6.05       NaN  2009
37  Eclipse Timing Variations       2         5767.00   NaN    130.72  2008
38  Eclipse Timing Variations       2         3321.00   NaN    130.72  2008
39  Eclipse Timing Variations       2         5573.55   NaN    500.00  2010
40  Eclipse Timing Variations       2         2883.50   NaN    500.00  2010
---------------------------e-----------------------------
---------------------------s----------------------------
Imaging
     method  number  orbit

In [ ]:
grouped.sum()

number  orbital_period        mass   distance  \
method                                                                         
Astrometry                          2    1.262360e+03     0.00000      35.75   
Eclipse Timing Variations          15    4.276480e+04    10.25000    1261.44   
Imaging                            50    1.418973e+06     0.00000    2166.91   
Microlensing                       27    2.207500e+04     0.00000   41440.00   
Orbital Brightness Modulation       5    2.127920e+00     0.00000    2360.00   
Pulsar Timing                      11    3.671511e+04     0.00000    1200.00   
Pulsation Timing Variations         1    1.170000e+03     0.00000       0.00   
Radial Velocity                   952    4.553151e+05  1341.65638   27348.11   
Transit                           776    8.377523e+03     1.47000  134242.77   
Transit Timing Variations           9    2.393505e+02     0.00000    3313.00   

                                  year  
method                                  
Astrometry                        4023  
Eclipse Timing Variations        18090  
Imaging                          76347  
Microlensing                     46225  
Orbital Brightness Modulation     6035  
Pulsar Timing                     9992  
Pulsation Timing Variations       2007  
Radial Velocity                1110158  
Transit                         798461  
Transit Timing Variations         8050

In [ ]:
grouped['year'].describe()

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

In [ ]:
planets

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [ ]:
sum(planets.isna().mass)
#planets.groupby('method').std().mass

522

In [ ]:
planets.loc[~planets.mass.isna(),:]

method  number  orbital_period    mass  distance  year
0    Radial Velocity       1         269.300   7.100     77.40  2006
1    Radial Velocity       1         874.774   2.210     56.95  2008
2    Radial Velocity       1         763.000   2.600     19.84  2011
3    Radial Velocity       1         326.030  19.400    110.62  2007
4    Radial Velocity       1         516.220  10.500    119.47  2009
..               ...     ...             ...     ...       ...   ...
784  Radial Velocity       3         580.000   0.947    135.00  2012
913  Radial Velocity       1         677.800  19.800       NaN  2007
914  Radial Velocity       1           6.958   0.340       NaN  2014
915  Radial Velocity       1           5.118   0.400       NaN  2014
916  Radial Velocity       1         121.710   1.540       NaN  2014

[513 rows x 6 columns]

In [ ]:
planets.mass.fillna(0, inplace=True)

In [ ]:
planets.groupby('method').std().mass

method
Astrometry                       0.000000
Eclipse Timing Variations        2.306753
Imaging                          0.000000
Microlensing                     0.000000
Orbital Brightness Modulation    0.000000
Pulsar Timing                    0.000000
Pulsation Timing Variations           NaN
Radial Velocity                  3.740900
Transit                          0.073777
Transit Timing Variations        0.000000
Name: mass, dtype: float64

In [ ]:
planets

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507   0.00    172.00  2006
1031          Transit       1        2.615864   0.00    148.00  2007
1032          Transit       1        3.191524   0.00    174.00  2007
1033          Transit       1        4.125083   0.00    293.00  2008
1034          Transit       1        4.187757   0.00    260.00  2008

[1035 rows x 6 columns]

In [ ]:
planets.groupby('method').mean().mass

method
Astrometry                       0.000000
Eclipse Timing Variations        1.138889
Imaging                          0.000000
Microlensing                     0.000000
Orbital Brightness Modulation    0.000000
Pulsar Timing                    0.000000
Pulsation Timing Variations      0.000000
Radial Velocity                  2.426142
Transit                          0.003703
Transit Timing Variations        0.000000
Name: mass, dtype: float64

In [ ]:
planets.groupby('method').sum()

number  orbital_period        mass   distance  \
method                                                                         
Astrometry                          2    1.262360e+03     0.00000      35.75   
Eclipse Timing Variations          15    4.276480e+04    10.25000    1261.44   
Imaging                            50    1.418973e+06     0.00000    2166.91   
Microlensing                       27    2.207500e+04     0.00000   41440.00   
Orbital Brightness Modulation       5    2.127920e+00     0.00000    2360.00   
Pulsar Timing                      11    3.671511e+04     0.00000    1200.00   
Pulsation Timing Variations         1    1.170000e+03     0.00000       0.00   
Radial Velocity                   952    4.553151e+05  1341.65638   27348.11   
Transit                           776    8.377523e+03     1.47000  134242.77   
Transit Timing Variations           9    2.393505e+02     0.00000    3313.00   

                                  year  
method                                  
Astrometry                        4023  
Eclipse Timing Variations        18090  
Imaging                          76347  
Microlensing                     46225  
Orbital Brightness Modulation     6035  
Pulsar Timing                     9992  
Pulsation Timing Variations       2007  
Radial Velocity                1110158  
Transit                         798461  
Transit Timing Variations         8050

In [ ]:
step1 = planets.groupby('method').std().mass < 2
step1

method
Astrometry                        True
Eclipse Timing Variations        False
Imaging                           True
Microlensing                      True
Orbital Brightness Modulation     True
Pulsar Timing                     True
Pulsation Timing Variations      False
Radial Velocity                  False
Transit                           True
Transit Timing Variations         True
Name: mass, dtype: bool

In [ ]:
step2 = step1.index[step1]
step2

Index(['Astrometry', 'Imaging', 'Microlensing',
       'Orbital Brightness Modulation', 'Pulsar Timing', 'Transit',
       'Transit Timing Variations'],
      dtype='object', name='method')

In [ ]:
step3 = planets.loc[planets.method.isin(step2), ["method","orbital_period"]]
step3

method  orbital_period
29    Imaging             NaN
30    Imaging             NaN
31    Imaging             NaN
33    Imaging             NaN
34    Imaging             NaN
...       ...             ...
1030  Transit        3.941507
1031  Transit        2.615864
1032  Transit        3.191524
1033  Transit        4.125083
1034  Transit        4.187757

[472 rows x 2 columns]

In [ ]:
step3.groupby("method").mean()

orbital_period
method                                       
Astrometry                         631.180000
Imaging                         118247.737500
Microlensing                      3153.571429
Orbital Brightness Modulation        0.709307
Pulsar Timing                     7343.021201
Transit                             21.102073
Transit Timing Variations           79.783500

In [ ]:
planets.head()

number  orbital_period   mass  distance  year
method                                                        
Radial Velocity       1         269.300   7.10     77.40  2006
Radial Velocity       1         874.774   2.21     56.95  2008
Radial Velocity       1         763.000   2.60     19.84  2011
Radial Velocity       1         326.030  19.40    110.62  2007
Radial Velocity       1         516.220  10.50    119.47  2009

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/test.csv')
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
df.Name

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...                     
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [ ]:
df.drop('Sex', axis=1, inplace=True)

In [ ]:
titanic = df

In [ ]:
titanic

PassengerId  Pclass                                          Name   Age  \
0            892       3                              Kelly, Mr. James  34.5   
1            893       3              Wilkes, Mrs. James (Ellen Needs)  47.0   
2            894       2                     Myles, Mr. Thomas Francis  62.0   
3            895       3                              Wirz, Mr. Albert  27.0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0   
..           ...     ...                                           ...   ...   
413         1305       3                            Spector, Mr. Woolf   NaN   
414         1306       1                  Oliva y Ocana, Dona. Fermina  39.0   
415         1307       3                  Saether, Mr. Simon Sivertsen  38.5   
416         1308       3                           Ware, Mr. Frederick   NaN   
417         1309       3                      Peter, Master. Michael J   NaN   

     SibSp  Parch              Ticket      Fare Cabin Embarked  
0        0      0              330911    7.8292   NaN        Q  
1        1      0              363272    7.0000   NaN        S  
2        0      0              240276    9.6875   NaN        Q  
3        0      0              315154    8.6625   NaN        S  
4        1      1             3101298   12.2875   NaN        S  
..     ...    ...                 ...       ...   ...      ...  
413      0      0           A.5. 3236    8.0500   NaN        S  
414      0      0            PC 17758  108.9000  C105        C  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0      0              359309    8.0500   NaN        S  
417      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

In [ ]:
#1. 남자여자별 pclass의 탑승인원
#2. 결혼유무별 생존자 수
#3. 나이는 (0~18,18~35,35~60,60~)에 따른 운임의 평균

In [ ]:
gender = np.where((titanic.Name.str.contains('Mrs')), 'female')
#  | titanic.Name.str.contains('Miss'

ValueError: ignored

In [ ]:
dt = titanic.loc[:,["Pclass","Name"]]
dt['gender'] = gender

In [ ]:
dt.groupby(['gender','Pclass']).count().Name

NameError: ignored

In [ ]:
# 2번 문제 
pd.cut(titanic.Age,[0,18,35,60,100])

0       (18.0, 35.0]
1       (35.0, 60.0]
2      (60.0, 100.0]
3       (18.0, 35.0]
4       (18.0, 35.0]
           ...      
413              NaN
414     (35.0, 60.0]
415     (35.0, 60.0]
416              NaN
417              NaN
Name: Age, Length: 418, dtype: category
Categories (4, interval[int64, right]): [(0, 18] < (18, 35] < (35, 60] < (60, 100]]