<a href="https://colab.research.google.com/github/changyui/changyui/blob/main/data_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 데이터셋은 피클 형태(파이썬 원시 변수 저장 형태) 이므로 Load 하는 방법 숙지
# 피클 X_400_5의 데이터는 플로우 앞 5개의 패킷이 함께 묶여있으며 각 패킷 앞 400bytes를 포함 (Load 후 shape 출력하고 확인)
# 각 모델의 입력은 단일입력이므로 2차원 형태어야하지만 데이터셋은 3차원임(플로우이므로.) 고로 차원을 줄이는 작업이 필요

In [ ]:
import pickle
import pandas as pd

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/NMlab/400_5_X.pickle', 'rb') as f:   
    dfx = pickle.load(f)

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/NMlab/400_5_Y.pickle', 'rb') as g:   
    dfy = pickle.load(g)

In [ ]:
dfx[100]

array([[[0.2705 ],
        [0.     ],
        [0.     ],
        ...,
        [0.     ],
        [0.     ],
        [0.     ]],

       [[0.2705 ],
        [0.     ],
        [0.     ],
        ...,
        [0.     ],
        [0.     ],
        [0.     ]],

       [[0.2705 ],
        [0.     ],
        [0.     ],
        ...,
        [0.     ],
        [0.     ],
        [0.     ]],

       [[0.2705 ],
        [0.     ],
        [0.00784],
        ...,
        [0.4666 ],
        [0.7803 ],
        [0.541  ]],

       [[0.2705 ],
        [0.     ],
        [0.     ],
        ...,
        [0.     ],
        [0.     ],
        [0.     ]]], dtype=float16)

In [ ]:
dfy[100]

array([1., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
dfx.shape

(27811, 5, 400, 1)

In [ ]:
dfy.shape

(27811, 6)

In [ ]:
# dfx = dfx[:,0,:,:]
# dfx.shape

(27811, 400, 1)

In [ ]:
dfx1 = df.reshape(-1,40,50,1)

In [ ]:
dfx1.shape

(27811, 40, 50, 1)

In [ ]:
dfx1[100]

array([[[0.2705],
        [0.    ],
        [0.    ],
        ...,
        [0.0392],
        [0.    ],
        [0.3647]],

       [[0.533 ],
        [0.6626],
        [0.    ],
        ...,
        [0.    ],
        [0.    ],
        [0.    ]],

       [[0.    ],
        [0.    ],
        [0.    ],
        ...,
        [0.    ],
        [0.    ],
        [0.    ]],

       ...,

       [[0.    ],
        [0.    ],
        [0.    ],
        ...,
        [0.    ],
        [0.    ],
        [0.    ]],

       [[0.    ],
        [0.    ],
        [0.    ],
        ...,
        [0.    ],
        [0.    ],
        [0.    ]],

       [[0.    ],
        [0.    ],
        [0.    ],
        ...,
        [0.    ],
        [0.    ],
        [0.    ]]], dtype=float16)

In [ ]:
from keras import models, layers
from keras import Input
from keras.models import Model, load_model
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers, initializers, regularizers, metrics
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import BatchNormalization, Conv2D, Activation, Dense, GlobalAveragePooling2D, MaxPooling2D, ZeroPadding2D, Add
 
import os
import matplotlib.pyplot as plt
import numpy as np
import math

from tensorflow.keras.applications.resnet50 import ResNet50

In [ ]:
model = ResNet50(include_top=True, weights=None, input_shape=(40,50,1), pooling=max, classes=6)

** 코멘트 **

(?, 5, 400, 1)

(5,400,1)

(400,1)[0] (20,20,1)
(400,1)[1]
(400,1)[2]
(400,1)[3]
(400,1)[4]


(2000,1)

(40,50,1)

a = Input(input_shape((?, 5, 400, 1)))
a = reshape(?,5,20,20,1)(a)

b = resmet50(input_shape=(20,20,1))(a[:,0])

In [ ]:
# train_images = dfx1
# train_labels = dfy

x = dfx1
y = dfy

# 훈련데이터 세트 분할
from sklearn.model_selection import train_test_split
train_images, valid_images, train_labels, valid_labels = train_test_split(x, y, stratify=y, test_size=0.2, random_state=42)

In [ ]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam') 
model.fit(train_images, train_labels, batch_size=64, epochs=10, validation_data=(valid_images, valid_labels))

Epoch 1/10
348/348 [==============================] - 2973s 9s/step - loss: 1.1878 - accuracy: 0.6032 - val_loss: 1.3411 - val_accuracy: 0.5432
Epoch 2/10
280/348 [=======================>......] - ETA: 9:36 - loss: 0.9261 - accuracy: 0.6464

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
